DigitalSGKWeb/Models/EntityFramework/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSGKWeb.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DEntities : DbContext
    {
        public DEntities()
            : base("name=DEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABPYRSubeler> ABPYRSubeler { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
    }
}

DigitalSGKWeb/Models/EntityFramework/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\msı\source\repos\DigitalSGKWeb\DigitalSGKWeb\Models\EntityFramework\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

DigitalSGKWeb/Models/EntityFramework/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

DigitalSGKWeb/Models/EntityFramework/MusterilerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DigitalSGKWeb.Models.EntityFramework
{
    public class MusterilerViewModel
    {
        public string MusteriKodu { get; set; }
       
        public string MusteriAdi { get; set; }
        public Nullable<short> Durumu { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<bool> isRutin { get; set; }
    }
}

DigitalSGKWeb/Controllers/MusterilerController.cs
using DigitalSGKWeb.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;

namespace DigitalSGKWeb.Controllers
{
    public class MusterilerController : Controller
    {
        DEntities db = new DEntities();
        // GET: Musteriler
        //public ActionResult Index()
        //{
        //    var degerler = db.Musteriler.ToList();
        //    return View(degerler);
        //}

        public ActionResult Index(string adara)
        {
           
            return View(db.Musteriler.Where(x=>x.MusteriAdi.Contains(adara)||adara==null).ToList());
        }


        public ActionResult MusteriSubesi(string id)
        {
            var model = db.ABPYRSubeler.Where(x=>x.Musteri==id).ToList();

            return View(model);
        }


        [HttpGet]
        public ActionResult MusteriEkleme()
        {
            return View();
        }
        [HttpPost]
        public ActionResult MusteriEkleme(Musteriler musteri)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("MusteriEklemePartial");
            }

            db.Musteriler.Add(musteri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult MusteriGetir(string id)
        {
            var deger = db.Musteriler.Find(id);
            
            return PartialView("Index", deger);
        }
        
        public ActionResult MusteriGetirPartial(string id)
        {
            var deger = db.Musteriler.Find(id);

            return PartialView("MusteriGetirPartial", deger);
        }
        //public ActionResult MusteriGuncelle(Musteriler musteriler)
        //{
        //    var degerler = db.Musteriler.Find(musteriler.MusteriKodu);
        //    degerler.MusteriAdi = musteriler.MusteriAdi;
        //    degerler.createdDate = musteriler.createdDate;
        //    degerler.Durumu = musteriler.Durumu;
        //    db.SaveChanges();
        //    ViewBag.dgr = degerler;
        //    return RedirectToAction("Index");
        //}
        public PartialViewResult MusteriGuncellemePartial()
        {
            return PartialView();
        }
        public PartialViewResult MusteriEklemePartial()
        {
            return PartialView();
        }

        public JsonResult GetMusterilerList()
        {
            List<MusterilerViewModel> MusList = db.Musteriler.Where(x => x.isRutin == false).Select(x => new MusterilerViewModel
            {
                MusteriKodu = x.MusteriKodu,
                MusteriAdi = x.MusteriAdi,
                Durumu = x.Durumu,
                createdDate = x.createdDate
            }).ToList();
            return Json(MusList, JsonRequestBehavior.AllowGet);
        }
    }
}

DigitalSGKWeb/Controllers/SubelerController.cs
using DigitalSGKWeb.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;


namespace DigitalSGKWeb.Controllers
{
    public class SubelerController : Controller
    {
        DEntities db = new DEntities();

        public ActionResult Index()
        {
            var degerler = db.ABPYRSubeler.ToList();
            return View(degerler);

        }


        [HttpGet]
        public ActionResult SubeEkle()
        {
            List<SelectListItem> degerler = (from i in db.Musteriler.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.MusteriAdi,
                                                 Value = i.MusteriKodu.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;
            return View();
        }
       [HttpPost]
        public ActionResult SubeEkle(ABPYRSubeler subeler)
        {
            var sube = db.Musteriler.Where(m => m.MusteriKodu == subeler.Musteriler.MusteriKodu).FirstOrDefault();
            subeler.Musteriler = sube;
            db.ABPYRSubeler.Add(subeler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SubeGetir(int id)
        {
            var sube = db.ABPYRSubeler.Find(id);
            return View("SubeGetir",sube);
        }

        public ActionResult SubeGuncelle(ABPYRSubeler subeler)
        {
            var degerler = db.ABPYRSubeler.Find(subeler.Id);
            degerler.SubeAdi = subeler.SubeAdi;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public PartialViewResult SubeEklemePartial()
        {
            List<SelectListItem> degerler = (from i in db.Musteriler.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.MusteriAdi,
                                                 Value = i.MusteriKodu.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;
            return PartialView();
        }
        public PartialViewResult SubeGuncellemePartial()
        {
            return PartialView();
        }
    }
}

DigitalSGKWeb/Views/Musteriler/Index.cshtml
@using DigitalSGKWeb.Models.EntityFramework
@model List<Musteriler>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>



<h2>Müşteriler Listesi</h2>


@Html.Action("MusteriEklemePartial")


<table id="myTable" class="table table-bordered">
    <thead>
        <tr>
            <th>Müşteri Kodu</th>
            <th>Müşteri Adı</th>
            <th>Oluşturulma Tarihi</th>
            <th>Müşteri Durumu</th>
            <th>Müşteri güncelleme</th>
            <th>Şubesi</th>
        </tr>
    </thead>
    <tbody>


        @foreach (var musteriler in Model)
        {
            <tr>
                <td>@musteriler.MusteriKodu</td>
                <td>@musteriler.MusteriAdi</td>
                <td>@musteriler.createdDate.Value.ToString("dd-MM-yyyy")</td>
                <td>@musteriler.Durumu</td>
                <td>@Html.Action("MusteriGuncellemePartial")</td>
                <td>@Html.ActionLink("Şubeleri göster", "MusteriSubesi", "Musteriler", new { id = musteriler.MusteriKodu }, new { @class = "btn btn-primary" })</td>
                <td></td>
            </tr>
        }


    </tbody>
</table>

<script>
    $(".deger").click(function () {
        var index1 = $(this).data("musteriadi");
        $(".modal-body>textarea").html(index1);

    });
</script>

<link href="~/Content/DataTables/css/dataTables.bootstrap4.css" rel="stylesheet" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="~/Content/bootstrap.css" rel="stylesheet" />

<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>
<script>
    $('#myTable').dataTable({
        "language": {
            "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Turkish.json"
        }
    });
</script>

DigitalSGKWeb/Views/Musteriler/MusteriEklemePartial.cshtml
@model DigitalSGKWeb.Models.EntityFramework.Musteriler



<!DOCTYPE html>

<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#Modal2">
    Müşteri ekle
</button>
<div class="modal" id="Modal2">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Müşteri Ekleme Ekranı</h4>
            </div>
            <form method="post" action="/Musteriler/MusteriEkleme">
                <div class="modal-body">
                    <label>Müşteri Adı</label>
                    <input type="text" name="MusteriAdi" class="form-control" required="" maxlength="200" />
                </div>
                <div class="modal-body">
                    <label>Müşteri Kodu</label>
                    <input type="text" name="MusteriKodu" class="form-control" required="" maxlength="200" />

                </div>
                <div class="modal-body">
                    <label for="party">Oluştrulma Tarihi</label>
                    <input id="party" type="text" name="createdDate" value="2017-06-01T08:30" />
                </div>
                <div class="modal-body">
                    <label for="balloons">Müşteri Durumu (1-100):</label>
                    <input type="number" id="balloons" name="Durumu" min="0" max="100" required />
                    <span class="validity"></span>
                </div>
                <div>
                    <input type="submit" onclick="myFunction()">
                    @*<br />
                    <button class="btn btn-info">Müşteriyi Kaydet</button>*@
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    function myFunction() {
        alert("Ekleme işlemi başarıyla gerçekleştirilmiştir.");
    }
</script>

DigitalSGKWeb/Views/Musteriler/MusteriGetir.cshtml
@model DigitalSGKWeb.Models.EntityFramework.Musteriler
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<!DOCTYPE html>
@using (Html.BeginForm("MusteriGuncelle", "Musteriler", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.MusteriKodu)
        @Html.TextBoxFor(m => m.MusteriKodu)
    </div>
}

DigitalSGKWeb/Views/Musteriler/MusteriGetirPartial.cshtml
@model DigitalSGKWeb.Models.EntityFramework.Musteriler


<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

<div class="modal" id="Modal4">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Müşteri Güncelleme Ekranı</h4>
            </div>
            <form method="post" action="/Musteriler/MusteriGetirPartial">
                <div class="modal-body">

                    @Html.LabelFor(m => m.MusteriAdi)
                    @Html.TextBoxFor(m => m.MusteriAdi)

                </div>
               
            </form>
        </div>
    </div>
</div>

DigitalSGKWeb/Views/Musteriler/MusteriGuncellemePartial.cshtml
@model DigitalSGKWeb.Models.EntityFramework.Musteriler


<!DOCTYPE html>


<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#Modal4">
    Müşteri GÜncelle
</button>
<div class="modal" id="Modal4">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Müşteri Güncelleme Ekranı</h4>
            </div>
            <form method="post" action="/Musteriler/MusteriGuncelle">
                <div class="modal-body">
                    @Html.LabelFor(m=>m.MusteriKodu)
                    @Html.TextBoxFor(m=>m.MusteriKodu)
                    @*<label>Müşteri Kodu</label>
                    <input type="text" name="MusteriKodu" class="form-control" required="" maxlength="200" />*@
                </div>
                <div class="modal-body">
                    <label>Müşteri Adı</label>
                    <input type="text" name="MusteriAdi" class="form-control" required="" maxlength="200" />
                </div>
                <div class="modal-body">
                    <label for="party">Oluştrulma Tarihi</label>
                    <input id="party" type="text" name="createdDate" value="2017-06-01T08:30" />
                </div>
                <div class="modal-body">
                    <label for="balloons">Müşteri Durumu (1-100):</label>
                    <input type="number" id="balloons" name="Durumu" min="0" max="100" required />
                    <span class="validity"></span>
                </div>
                <div>
                    <input type="submit" onclick="myFunction()">

                   
                </div>
            </form>
        </div>
    </div>
</div>


<script>
    function myFunction() {
        alert("Güncelleme işlemi başarıyla gerçekleştirilmiştir.");
    }
</script>

DigitalSGKWeb/Views/Musteriler/MusteriSubesi.cshtml
@model IEnumerable<DigitalSGKWeb.Models.EntityFramework.ABPYRSubeler>
@{
    ViewBag.Title = "MusteriSubesi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>MusteriSubesi</h2>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Müşteri Adı</th>
            <th>Müşteri Kodu</th>
            <th>Müşterinin şubesinin adı</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var subeler in Model)
        {
            <tr>
                <td>@subeler.Musteriler.MusteriAdi</td>
                <td>@subeler.Musteriler.MusteriKodu</td>
                <td>@subeler.SubeAdi</td>
            </tr>
        }

    </tbody>
</table>

DigitalSGKWeb/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>_Layout</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/dataTables.bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    @Html.Partial("_Navbar")
    <div class="container">
        @RenderBody()
    </div>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/DataTables/dataTables.bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-1.7.min.js"></script>
</body>
</html>

DigitalSGKWeb/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-sm bg-light">

    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">DigitalSGK-WEB</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="/Subeler">Şubeler</a></li>
            <li><a href="/Musteriler">Müşteriler</a></li>
        </ul>
    </div>


</nav>

DigitalSGKWeb/Views/Subeler/Index.cshtml
@using DigitalSGKWeb.Models.EntityFramework
@model List<ABPYRSubeler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

@*<a href="/Subeler/SubeEkle" class="btn btn-primary">Şube ekle</a>*@

@Html.Action("SubeEklemePartial")

<h2>Şubeler Listesi</h2>

<table id="myTable" class="table table-bordered">
    <thead>
        <tr>
            <th>Şube Kodu</th>
            <th>Şube Adı</th>
            <th>Müşteri Kodu</th>
            <th>Müşteri Adı</th>
            <th>Şube adını güncelleme</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var subeler in Model)
        {
            <tr>
                <td>@subeler.SubeKodu</td>
                <td>@subeler.SubeAdi</td>
                <td>@subeler.Musteriler.MusteriKodu</td>
                <td>@subeler.Musteriler.MusteriAdi</td>
                @*<td><a class="btn btn-primary" href="/Subeler/SubeGetir/@subeler.Id">Güncelle</a></td>*@
                <td>@Html.Action("SubeGuncellemePartial")</td>
            </tr>
        }

    </tbody>
</table>

<link href="~/Content/DataTables/css/dataTables.bootstrap4.css" rel="stylesheet" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="~/Content/bootstrap.css" rel="stylesheet" />

<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>
<script>
    $('#myTable').dataTable({
        "language": {
            "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Turkish.json"
        }
    });
</script>

DigitalSGKWeb/Views/Subeler/SubeEkle.cshtml
@model DigitalSGKWeb.Models.EntityFramework.ABPYRSubeler
@{
    ViewBag.Title = "SubeEkle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#Modal1">
    Şube ekle
</button>
<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Şube Ekleme Ekranı</h4>
            </div>
            <form method="post" action="/Subeler/SubeEkle">
                <div class="modal-body">
                    <label>Şube Adı</label>
                    <input type="text" name="SubeAdi" class="form-control" />
                </div>
                <div class="modal-body">
                    <label>Şube Kodu</label>
                    <input type="text" name="SubeKodu" class="form-control" />

                </div>
                <div class="modal-body">
                    <label>Müşteri Seçiniz</label>
                    @Html.DropDownListFor(m => m.Musteriler.MusteriKodu, (List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })
                    <br />
                    <button class="btn btn-info" onclick="myFunction()">Şubeyi Kaydet</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    function myFunction() {
        alert("Güncelleme işlemi başarıyla gerçekleştirilmiştir.");
    }
</script>

DigitalSGKWeb/Views/Subeler/SubeEklemePartial.cshtml
@model DigitalSGKWeb.Models.EntityFramework.ABPYRSubeler

<!DOCTYPE html>

<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#Modal1">
    Şube ekle
</button>
<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Şube Ekleme Ekranı</h4>
            </div>
            <form method="post" action="/Subeler/SubeEkle">
                <div class="modal-body">
                    <label>Şube Adı</label>
                    <input type="text" name="SubeAdi" class="form-control" required="" maxlength="200" />
                </div>
                <div class="modal-body">
                    <label>Şube Kodu</label>
                    <input type="text" name="SubeKodu" class="form-control" required="" maxlength="50" />

                </div>
                <div class="modal-body">
                        <label>Müşteri Seçiniz</label>
                        @Html.DropDownListFor(m => m.Musteriler.MusteriKodu, (List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })
                        <br />
                        @*<button class="btn btn-info" onclick="myFunction()">Şubeyi Kaydet</button>*@
                    <input type="button" value="Kaydet" name="alertMessage" id="mesaj" />
                    </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    //function myFunction() {
    //    swal("Şube başarıyla kaydedilmiştir....!", "You clicked the button!", "success");
    //}
    $(document).ready(function () {
        $("#mesaj").click(function () {
            swal("Şube başarıyla kaydedilmiştir....!", "You clicked the button!", "success");
        });
    });
</script>

DigitalSGKWeb/Views/Subeler/SubeGetir.cshtml
@model DigitalSGKWeb.Models.EntityFramework.ABPYRSubeler
@{
    ViewBag.Title = "SubeGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#Modal3">
    Şube GÜncelle
</button>
<div class="modal" id="Modal3">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Şube Güncelleme Ekranı</h4>
            </div>
            <form method="post" action="/Subeler/SubeGuncelle">
                <div class="modal-body">
                    <label>Şube Adı</label>
                    <input type="text" name="SubeAdi" class="form-control" />
                </div>
                <div class="modal-body">
                    <label>Şube Numarası</label>
                    <input type="text" name="Id" class="form-control" />
                    <br />
                    <button class="btn btn-info">Şubeyi Kaydet</button>
                </div>

            </form>
        </div>
    </div>
</div>